apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-frontend
  labels:
    app: fortune-frontend
spec:
  selector:
    matchLabels:
      app: fortune-frontend
  template:
    metadata:
      labels:
        app: fortune-frontend
    spec:
      containers:
      - name: fortune-frontend
        env:
          - name: BACKEND_DNS
            value: fortune-backend
        image: ghcr.io/amatzen/se05-cd-simplefortunecookie/frontend:FRONTEND_VERSION
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: fortune-frontend
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fortune-frontend
  labels:
    app: fortune-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: fortune-frontend