name: Production release CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release'
        required: true

jobs:
  deploy-to-production:
    name: Deploy to production
    runs-on: [self-hosted, linux, x64, production]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Inject release versions
      run: |
        sed -i "s/BACKEND_VERSION/${{ github.event.inputs.version }}/g" backend.yml
        sed -i "s/FRONTEND_VERSION/${{ github.event.inputs.version }}/g" frontend.yml
    - name: Apply manifests
      run: |
        kubectl apply -f ./kubernetes-manifests