on:
  push:
    branches:
      - main
name: Release Manager
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          token: ${{ secrets.BOT_PAT }}
          command: github-release
