name: Release CD

on:
  release:
    branches:
      - main
  push:
    branches:
      - 5-push-container-to-gh-packages

jobs:

  build_image_backend:
    name: Build backend image
    runs-on: ubuntu-22.04
    #if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout backend
      uses: actions/checkout@v2
      with:
        path: 'backend'
    - name: Setup Docker
      id: setup-docker
      uses: ./.github/workflows/partial-docker
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        image_name: ${{ github.repository }}/backend
    - name: Build and Publish
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ steps.setup-docker.outputs.image_name }}:${{ github.ref_name }}

  build_image_frontend:
    name: Build frontend image
    runs-on: ubuntu-22.04
    #if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Publish
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ env.IMAGE_PREFIX }}/frontend:${{ github.ref_name }}

  
